### ISSUE TITLE
Invalid Destination Path error when install nodejs app

### ISSUE THREAD

**Issue by GooDogFun** [JLFdzDev/hestiacp-nodejs#1]
During installation, I encountered an error with the Node.js app deployment process.
Your assistance would be greatly appreciated.

![image](https://github.com/JLFdzDev/hestiacp-nodejs/assets/165798680/35d10ae3-515c-492c-8226-8d8d9da17e5a)

**Comment by skylarng89** [comment]
Hey @GooDogFun the reason it's failing is because your Hestia user doesn't have the SSH access set to "bash". It's a requirement because the plugin needs bash access.

Just go to your user and change the SSH Access to bash:
![image](https://github.com/JLFdzDev/hestiacp-nodejs/assets/151549884/ab45f332-7152-4f9e-bf5a-aac78373f40c)

**Comment by JLFdzDev** [comment]
@skylarng89 thanks for your help 😀
